name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
      - if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Tokyo
      - uses: lowlighter/metrics@latest
        with:
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
      - uses: lowlighter/metrics@latest
        with:
          config_presets: "@lunar-red"
      - uses: lowlighter/metrics@latest
        with:
          base: header
          extras_js: |
            document.querySelectorAll("h2")?.forEach(h2 => h2.remove())
      - uses: lowlighter/metrics@latest
        with:
          config_output: insights

