name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Tokyo
      - uses: lowlighter/metrics@latest
        with:
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
      - uses: lowlighter/metrics@latest
        with:
          config_presets: "@lunar-red"
      - uses: lowlighter/metrics@latest
        with:
          base: header
          extras_js: |
            document.querySelectorAll("h2")?.forEach(h2 => h2.remove())
      - uses: lowlighter/metrics@latest
        with:
          config_output: insights

